<?php
/**
 * AccountBalanceReplyRowTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 星辰
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com_kingdee_service;

/**
 * AccountBalanceReplyRowTest Class Doc Comment
 *
 * @category    Class
 * @description AccountBalanceReplyRow
 * @package     com_kingdee_service
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountBalanceReplyRowTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccountBalanceReplyRow"
     */
    public function testAccountBalanceReplyRow()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "account_no"
     */
    public function testPropertyAccountNo()
    {
    }

    /**
     * Test attribute "account_name"
     */
    public function testPropertyAccountName()
    {
    }

    /**
     * Test attribute "currency_name"
     */
    public function testPropertyCurrencyName()
    {
    }

    /**
     * Test attribute "detail_id"
     */
    public function testPropertyDetailId()
    {
    }

    /**
     * Test attribute "begin_bal"
     */
    public function testPropertyBeginBal()
    {
    }

    /**
     * Test attribute "begin_bal_for"
     */
    public function testPropertyBeginBalFor()
    {
    }

    /**
     * Test attribute "begin_dc"
     */
    public function testPropertyBeginDc()
    {
    }

    /**
     * Test attribute "debit"
     */
    public function testPropertyDebit()
    {
    }

    /**
     * Test attribute "debit_for"
     */
    public function testPropertyDebitFor()
    {
    }

    /**
     * Test attribute "credit"
     */
    public function testPropertyCredit()
    {
    }

    /**
     * Test attribute "credit_for"
     */
    public function testPropertyCreditFor()
    {
    }

    /**
     * Test attribute "ytd_debit"
     */
    public function testPropertyYtdDebit()
    {
    }

    /**
     * Test attribute "ytd_debit_for"
     */
    public function testPropertyYtdDebitFor()
    {
    }

    /**
     * Test attribute "ytd_credit"
     */
    public function testPropertyYtdCredit()
    {
    }

    /**
     * Test attribute "ytd_credit_for"
     */
    public function testPropertyYtdCreditFor()
    {
    }

    /**
     * Test attribute "end_bal"
     */
    public function testPropertyEndBal()
    {
    }

    /**
     * Test attribute "end_bal_for"
     */
    public function testPropertyEndBalFor()
    {
    }

    /**
     * Test attribute "end_dc"
     */
    public function testPropertyEndDc()
    {
    }
}
