<?php
/**
 * ArCreditSaveRequestSourceBillEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 星辰
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com_kingdee_service;

/**
 * ArCreditSaveRequestSourceBillEntryTest Class Doc Comment
 *
 * @category    Class
 * @description ArCreditSaveRequestSourceBillEntry
 * @package     com_kingdee_service
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ArCreditSaveRequestSourceBillEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ArCreditSaveRequestSourceBillEntry"
     */
    public function testArCreditSaveRequestSourceBillEntry()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "src_bill_id"
     */
    public function testPropertySrcBillId()
    {
    }

    /**
     * Test attribute "src_bill_type_id"
     */
    public function testPropertySrcBillTypeId()
    {
    }

    /**
     * Test attribute "cur_settle_amount"
     */
    public function testPropertyCurSettleAmount()
    {
    }

    /**
     * Test attribute "src_comment"
     */
    public function testPropertySrcComment()
    {
    }
}
