<?php
/**
 * CardDetailReplyExpenselistTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 星辰
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com_kingdee_service;

/**
 * CardDetailReplyExpenselistTest Class Doc Comment
 *
 * @category    Class
 * @description CardDetailReplyExpenselist
 * @package     com_kingdee_service
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CardDetailReplyExpenselistTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CardDetailReplyExpenselist"
     */
    public function testCardDetailReplyExpenselist()
    {
    }

    /**
     * Test attribute "seq"
     */
    public function testPropertySeq()
    {
    }

    /**
     * Test attribute "expense_list_dept_id"
     */
    public function testPropertyExpenseListDeptId()
    {
    }

    /**
     * Test attribute "expense_list_dept_number"
     */
    public function testPropertyExpenseListDeptNumber()
    {
    }

    /**
     * Test attribute "expense_list_dept_name"
     */
    public function testPropertyExpenseListDeptName()
    {
    }

    /**
     * Test attribute "expense_list_acct_id"
     */
    public function testPropertyExpenseListAcctId()
    {
    }

    /**
     * Test attribute "expense_list_acct_number"
     */
    public function testPropertyExpenseListAcctNumber()
    {
    }

    /**
     * Test attribute "expense_list_acct_name"
     */
    public function testPropertyExpenseListAcctName()
    {
    }

    /**
     * Test attribute "expense_list_detail_id"
     */
    public function testPropertyExpenseListDetailId()
    {
    }

    /**
     * Test attribute "expense_list_percent"
     */
    public function testPropertyExpenseListPercent()
    {
    }

    /**
     * Test attribute "expense_list_all_pct"
     */
    public function testPropertyExpenseListAllPct()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }
}
