<?php
/**
 * CustomerDetailResTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 星辰
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com_kingdee_service;

/**
 * CustomerDetailResTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerDetailRes
 * @package     com_kingdee_service
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerDetailResTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerDetailRes"
     */
    public function testCustomerDetailRes()
    {
    }

    /**
     * Test attribute "modify_time"
     */
    public function testPropertyModifyTime()
    {
    }

    /**
     * Test attribute "invoice_name"
     */
    public function testPropertyInvoiceName()
    {
    }

    /**
     * Test attribute "taxpayer_no"
     */
    public function testPropertyTaxpayerNo()
    {
    }

    /**
     * Test attribute "bank_account"
     */
    public function testPropertyBankAccount()
    {
    }

    /**
     * Test attribute "bank"
     */
    public function testPropertyBank()
    {
    }

    /**
     * Test attribute "account_open_addr"
     */
    public function testPropertyAccountOpenAddr()
    {
    }

    /**
     * Test attribute "invoice_type"
     */
    public function testPropertyInvoiceType()
    {
    }

    /**
     * Test attribute "remark"
     */
    public function testPropertyRemark()
    {
    }

    /**
     * Test attribute "country_id"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "country_number"
     */
    public function testPropertyCountryNumber()
    {
    }

    /**
     * Test attribute "country_name"
     */
    public function testPropertyCountryName()
    {
    }

    /**
     * Test attribute "province_id"
     */
    public function testPropertyProvinceId()
    {
    }

    /**
     * Test attribute "province_name"
     */
    public function testPropertyProvinceName()
    {
    }

    /**
     * Test attribute "province_number"
     */
    public function testPropertyProvinceNumber()
    {
    }

    /**
     * Test attribute "city_id"
     */
    public function testPropertyCityId()
    {
    }

    /**
     * Test attribute "city_number"
     */
    public function testPropertyCityNumber()
    {
    }

    /**
     * Test attribute "city_name"
     */
    public function testPropertyCityName()
    {
    }

    /**
     * Test attribute "district_id"
     */
    public function testPropertyDistrictId()
    {
    }

    /**
     * Test attribute "district_number"
     */
    public function testPropertyDistrictNumber()
    {
    }

    /**
     * Test attribute "district_name"
     */
    public function testPropertyDistrictName()
    {
    }

    /**
     * Test attribute "sale_dept_id"
     */
    public function testPropertySaleDeptId()
    {
    }

    /**
     * Test attribute "sale_dept_number"
     */
    public function testPropertySaleDeptNumber()
    {
    }

    /**
     * Test attribute "sale_dept_name"
     */
    public function testPropertySaleDeptName()
    {
    }

    /**
     * Test attribute "c_level_id"
     */
    public function testPropertyCLevelId()
    {
    }

    /**
     * Test attribute "c_level_name"
     */
    public function testPropertyCLevelName()
    {
    }

    /**
     * Test attribute "c_level_number"
     */
    public function testPropertyCLevelNumber()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "rate"
     */
    public function testPropertyRate()
    {
    }

    /**
     * Test attribute "enable"
     */
    public function testPropertyEnable()
    {
    }

    /**
     * Test attribute "bomentity"
     */
    public function testPropertyBomentity()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "addr"
     */
    public function testPropertyAddr()
    {
    }

    /**
     * Test attribute "group_id"
     */
    public function testPropertyGroupId()
    {
    }

    /**
     * Test attribute "group_name"
     */
    public function testPropertyGroupName()
    {
    }

    /**
     * Test attribute "group_number"
     */
    public function testPropertyGroupNumber()
    {
    }

    /**
     * Test attribute "create_time"
     */
    public function testPropertyCreateTime()
    {
    }

    /**
     * Test attribute "creater_field_name"
     */
    public function testPropertyCreaterFieldName()
    {
    }

    /**
     * Test attribute "saler_id"
     */
    public function testPropertySalerId()
    {
    }

    /**
     * Test attribute "saler_name"
     */
    public function testPropertySalerName()
    {
    }

    /**
     * Test attribute "saler_number"
     */
    public function testPropertySalerNumber()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "custom_field"
     */
    public function testPropertyCustomField()
    {
    }
}
