<?php
/**
 * FaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 星辰
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com_kingdee_service;

/**
 * FaTest Class Doc Comment
 *
 * @category    Class
 * @description Fa
 * @package     com_kingdee_service
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Fa"
     */
    public function testFa()
    {
    }

    /**
     * Test attribute "start_year"
     */
    public function testPropertyStartYear()
    {
    }

    /**
     * Test attribute "start_period"
     */
    public function testPropertyStartPeriod()
    {
    }

    /**
     * Test attribute "current_year"
     */
    public function testPropertyCurrentYear()
    {
    }

    /**
     * Test attribute "current_period"
     */
    public function testPropertyCurrentPeriod()
    {
    }

    /**
     * Test attribute "with_gl"
     */
    public function testPropertyWithGl()
    {
    }

    /**
     * Test attribute "close_with_gl"
     */
    public function testPropertyCloseWithGl()
    {
    }

    /**
     * Test attribute "depreciate_field"
     */
    public function testPropertyDepreciateField()
    {
    }
}
