<?php
/**
 * InboundSaveReqTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 星辰
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com_kingdee_service;

/**
 * InboundSaveReqTest Class Doc Comment
 *
 * @category    Class
 * @description InboundSaveReq
 * @package     com_kingdee_service
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InboundSaveReqTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InboundSaveReq"
     */
    public function testInboundSaveReq()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "bill_no"
     */
    public function testPropertyBillNo()
    {
    }

    /**
     * Test attribute "bill_date"
     */
    public function testPropertyBillDate()
    {
    }

    /**
     * Test attribute "trans_type"
     */
    public function testPropertyTransType()
    {
    }

    /**
     * Test attribute "remark"
     */
    public function testPropertyRemark()
    {
    }

    /**
     * Test attribute "dept_id"
     */
    public function testPropertyDeptId()
    {
    }

    /**
     * Test attribute "dept_number"
     */
    public function testPropertyDeptNumber()
    {
    }

    /**
     * Test attribute "emp_id"
     */
    public function testPropertyEmpId()
    {
    }

    /**
     * Test attribute "emp_number"
     */
    public function testPropertyEmpNumber()
    {
    }

    /**
     * Test attribute "supplier_id"
     */
    public function testPropertySupplierId()
    {
    }

    /**
     * Test attribute "supplier_number"
     */
    public function testPropertySupplierNumber()
    {
    }

    /**
     * Test attribute "contact_info"
     */
    public function testPropertyContactInfo()
    {
    }

    /**
     * Test attribute "currency_id"
     */
    public function testPropertyCurrencyId()
    {
    }

    /**
     * Test attribute "currency_number"
     */
    public function testPropertyCurrencyNumber()
    {
    }

    /**
     * Test attribute "exchange_rate"
     */
    public function testPropertyExchangeRate()
    {
    }

    /**
     * Test attribute "dispatcher_phone"
     */
    public function testPropertyDispatcherPhone()
    {
    }

    /**
     * Test attribute "dispatcher_country_id"
     */
    public function testPropertyDispatcherCountryId()
    {
    }

    /**
     * Test attribute "dispatcher_province_id"
     */
    public function testPropertyDispatcherProvinceId()
    {
    }

    /**
     * Test attribute "dispatcher_city_id"
     */
    public function testPropertyDispatcherCityId()
    {
    }

    /**
     * Test attribute "dispatcher_district"
     */
    public function testPropertyDispatcherDistrict()
    {
    }

    /**
     * Test attribute "dispatcher_address"
     */
    public function testPropertyDispatcherAddress()
    {
    }

    /**
     * Test attribute "diff_amount"
     */
    public function testPropertyDiffAmount()
    {
    }

    /**
     * Test attribute "total_amount"
     */
    public function testPropertyTotalAmount()
    {
    }

    /**
     * Test attribute "cost_fee_entity"
     */
    public function testPropertyCostFeeEntity()
    {
    }

    /**
     * Test attribute "ignore_warn"
     */
    public function testPropertyIgnoreWarn()
    {
    }

    /**
     * Test attribute "payment_entry"
     */
    public function testPropertyPaymentEntry()
    {
    }

    /**
     * Test attribute "material_entity"
     */
    public function testPropertyMaterialEntity()
    {
    }

    /**
     * Test attribute "attachments_url"
     */
    public function testPropertyAttachmentsUrl()
    {
    }

    /**
     * Test attribute "outside_pk_id"
     */
    public function testPropertyOutsidePkId()
    {
    }

    /**
     * Test attribute "deduction_balance"
     */
    public function testPropertyDeductionBalance()
    {
    }

    /**
     * Test attribute "deduction_entry"
     */
    public function testPropertyDeductionEntry()
    {
    }

    /**
     * Test attribute "reverse_condition_calculate"
     */
    public function testPropertyReverseConditionCalculate()
    {
    }

    /**
     * Test attribute "custom_field"
     */
    public function testPropertyCustomField()
    {
    }

    /**
     * Test attribute "operation_key"
     */
    public function testPropertyOperationKey()
    {
    }
}
