<?php
/**
 * MeasureUnitDetailResTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 星辰
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com_kingdee_service;

/**
 * MeasureUnitDetailResTest Class Doc Comment
 *
 * @category    Class
 * @description MeasureUnitDetailRes
 * @package     com_kingdee_service
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MeasureUnitDetailResTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MeasureUnitDetailRes"
     */
    public function testMeasureUnitDetailRes()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "long_number"
     */
    public function testPropertyLongNumber()
    {
    }

    /**
     * Test attribute "enable"
     */
    public function testPropertyEnable()
    {
    }

    /**
     * Test attribute "create_time"
     */
    public function testPropertyCreateTime()
    {
    }

    /**
     * Test attribute "creator_id"
     */
    public function testPropertyCreatorId()
    {
    }

    /**
     * Test attribute "modify_time"
     */
    public function testPropertyModifyTime()
    {
    }

    /**
     * Test attribute "modifier_id"
     */
    public function testPropertyModifierId()
    {
    }

    /**
     * Test attribute "is_leaf"
     */
    public function testPropertyIsLeaf()
    {
    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {
    }

    /**
     * Test attribute "precision"
     */
    public function testPropertyPrecision()
    {
    }

    /**
     * Test attribute "precision_account"
     */
    public function testPropertyPrecisionAccount()
    {
    }

    /**
     * Test attribute "conversion_type"
     */
    public function testPropertyConversionType()
    {
    }
}
