<?php
/**
 * RetailBillListReqTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 星辰
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com_kingdee_service;

/**
 * RetailBillListReqTest Class Doc Comment
 *
 * @category    Class
 * @description RetailBillListReq
 * @package     com_kingdee_service
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RetailBillListReqTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RetailBillListReq"
     */
    public function testRetailBillListReq()
    {
    }

    /**
     * Test attribute "member_id"
     */
    public function testPropertyMemberId()
    {
    }

    /**
     * Test attribute "store_id"
     */
    public function testPropertyStoreId()
    {
    }

    /**
     * Test attribute "cashier_id"
     */
    public function testPropertyCashierId()
    {
    }

    /**
     * Test attribute "fetch_detail"
     */
    public function testPropertyFetchDetail()
    {
    }

    /**
     * Test attribute "biz_type"
     */
    public function testPropertyBizType()
    {
    }

    /**
     * Test attribute "end_time"
     */
    public function testPropertyEndTime()
    {
    }

    /**
     * Test attribute "bill_no"
     */
    public function testPropertyBillNo()
    {
    }

    /**
     * Test attribute "page_no"
     */
    public function testPropertyPageNo()
    {
    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {
    }

    /**
     * Test attribute "product_ids"
     */
    public function testPropertyProductIds()
    {
    }

    /**
     * Test attribute "pos_id"
     */
    public function testPropertyPosId()
    {
    }

    /**
     * Test attribute "ids"
     */
    public function testPropertyIds()
    {
    }

    /**
     * Test attribute "page_size"
     */
    public function testPropertyPageSize()
    {
    }
}
