<?php
/**
 * SupplierDetailResTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 星辰
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com_kingdee_service;

/**
 * SupplierDetailResTest Class Doc Comment
 *
 * @category    Class
 * @description SupplierDetailRes
 * @package     com_kingdee_service
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SupplierDetailResTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SupplierDetailRes"
     */
    public function testSupplierDetailRes()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "enable"
     */
    public function testPropertyEnable()
    {
    }

    /**
     * Test attribute "group_name"
     */
    public function testPropertyGroupName()
    {
    }

    /**
     * Test attribute "saler_name"
     */
    public function testPropertySalerName()
    {
    }

    /**
     * Test attribute "sale_dept_name"
     */
    public function testPropertySaleDeptName()
    {
    }

    /**
     * Test attribute "bom_entity"
     */
    public function testPropertyBomEntity()
    {
    }

    /**
     * Test attribute "custom_field"
     */
    public function testPropertyCustomField()
    {
    }

    /**
     * Test attribute "taxpayer_no"
     */
    public function testPropertyTaxpayerNo()
    {
    }
}
