<?php
/**
 * SalaryItemsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 星辰
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace com_kingdee_service;

use \com_kingdee_service\Configuration;
use \com_kingdee_service\ApiException;
use \com_kingdee_service\ObjectSerializer;

/**
 * SalaryItemsApiTest Class Doc Comment
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SalaryItemsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for salaryItemsSalaryItemsList
     *
     * 工资项目列表;获取工资项目列表;1.0.2.
     *
     */
    public function testSalaryItemsSalaryItemsList()
    {
    }

    /**
     * Test case for salaryItemsSalaryItemsSave
     *
     * 工资项目保存;工资项目修改及增加;1.0.2.
     *
     */
    public function testSalaryItemsSalaryItemsSave()
    {
    }
}
