<?php
/**
 * AccountList
 *
 * PHP version 5
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 星辰
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace com_kingdee_service\data\entity;

use \ArrayAccess;
use \com_kingdee_service\ObjectSerializer;

/**
 * AccountList Class Doc Comment
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountList implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AccountList';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'pid' => 'string',
        'number' => 'string',
        'name' => 'string',
        'full_name' => 'string',
        'dc' => 'int',
        'is_leaf' => 'int',
        'level' => 'int',
        'help_code' => 'string',
        'enable' => 'int',
        'is_cash' => 'int',
        'is_bank' => 'int',
        'is_cash_equivalent' => 'int',
        'is_qty' => 'int',
        'is_currency' => 'int',
        'is_assist' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'pid' => null,
        'number' => null,
        'name' => null,
        'full_name' => null,
        'dc' => 'int32',
        'is_leaf' => 'int32',
        'level' => 'int32',
        'help_code' => null,
        'enable' => 'int32',
        'is_cash' => 'int32',
        'is_bank' => 'int32',
        'is_cash_equivalent' => 'int32',
        'is_qty' => 'int32',
        'is_currency' => 'int32',
        'is_assist' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'pid' => 'pid',
        'number' => 'number',
        'name' => 'name',
        'full_name' => 'full_name',
        'dc' => 'dc',
        'is_leaf' => 'is_leaf',
        'level' => 'level',
        'help_code' => 'help_code',
        'enable' => 'enable',
        'is_cash' => 'is_cash',
        'is_bank' => 'is_bank',
        'is_cash_equivalent' => 'is_cash_equivalent',
        'is_qty' => 'is_qty',
        'is_currency' => 'is_currency',
        'is_assist' => 'is_assist'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'pid' => 'setPid',
        'number' => 'setNumber',
        'name' => 'setName',
        'full_name' => 'setFullName',
        'dc' => 'setDc',
        'is_leaf' => 'setIsLeaf',
        'level' => 'setLevel',
        'help_code' => 'setHelpCode',
        'enable' => 'setEnable',
        'is_cash' => 'setIsCash',
        'is_bank' => 'setIsBank',
        'is_cash_equivalent' => 'setIsCashEquivalent',
        'is_qty' => 'setIsQty',
        'is_currency' => 'setIsCurrency',
        'is_assist' => 'setIsAssist'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'pid' => 'getPid',
        'number' => 'getNumber',
        'name' => 'getName',
        'full_name' => 'getFullName',
        'dc' => 'getDc',
        'is_leaf' => 'getIsLeaf',
        'level' => 'getLevel',
        'help_code' => 'getHelpCode',
        'enable' => 'getEnable',
        'is_cash' => 'getIsCash',
        'is_bank' => 'getIsBank',
        'is_cash_equivalent' => 'getIsCashEquivalent',
        'is_qty' => 'getIsQty',
        'is_currency' => 'getIsCurrency',
        'is_assist' => 'getIsAssist'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['pid'] = isset($data['pid']) ? $data['pid'] : null;
        $this->container['number'] = isset($data['number']) ? $data['number'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['full_name'] = isset($data['full_name']) ? $data['full_name'] : null;
        $this->container['dc'] = isset($data['dc']) ? $data['dc'] : null;
        $this->container['is_leaf'] = isset($data['is_leaf']) ? $data['is_leaf'] : null;
        $this->container['level'] = isset($data['level']) ? $data['level'] : null;
        $this->container['help_code'] = isset($data['help_code']) ? $data['help_code'] : null;
        $this->container['enable'] = isset($data['enable']) ? $data['enable'] : null;
        $this->container['is_cash'] = isset($data['is_cash']) ? $data['is_cash'] : null;
        $this->container['is_bank'] = isset($data['is_bank']) ? $data['is_bank'] : null;
        $this->container['is_cash_equivalent'] = isset($data['is_cash_equivalent']) ? $data['is_cash_equivalent'] : null;
        $this->container['is_qty'] = isset($data['is_qty']) ? $data['is_qty'] : null;
        $this->container['is_currency'] = isset($data['is_currency']) ? $data['is_currency'] : null;
        $this->container['is_assist'] = isset($data['is_assist']) ? $data['is_assist'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets pid
     *
     * @return string
     */
    public function getPid()
    {
        return $this->container['pid'];
    }

    /**
     * Sets pid
     *
     * @param string $pid pid
     *
     * @return $this
     */
    public function setPid($pid)
    {
        $this->container['pid'] = $pid;

        return $this;
    }

    /**
     * Gets number
     *
     * @return string
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param string $number number
     *
     * @return $this
     */
    public function setNumber($number)
    {
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets full_name
     *
     * @return string
     */
    public function getFullName()
    {
        return $this->container['full_name'];
    }

    /**
     * Sets full_name
     *
     * @param string $full_name full_name
     *
     * @return $this
     */
    public function setFullName($full_name)
    {
        $this->container['full_name'] = $full_name;

        return $this;
    }

    /**
     * Gets dc
     *
     * @return int
     */
    public function getDc()
    {
        return $this->container['dc'];
    }

    /**
     * Sets dc
     *
     * @param int $dc dc
     *
     * @return $this
     */
    public function setDc($dc)
    {
        $this->container['dc'] = $dc;

        return $this;
    }

    /**
     * Gets is_leaf
     *
     * @return int
     */
    public function getIsLeaf()
    {
        return $this->container['is_leaf'];
    }

    /**
     * Sets is_leaf
     *
     * @param int $is_leaf is_leaf
     *
     * @return $this
     */
    public function setIsLeaf($is_leaf)
    {
        $this->container['is_leaf'] = $is_leaf;

        return $this;
    }

    /**
     * Gets level
     *
     * @return int
     */
    public function getLevel()
    {
        return $this->container['level'];
    }

    /**
     * Sets level
     *
     * @param int $level level
     *
     * @return $this
     */
    public function setLevel($level)
    {
        $this->container['level'] = $level;

        return $this;
    }

    /**
     * Gets help_code
     *
     * @return string
     */
    public function getHelpCode()
    {
        return $this->container['help_code'];
    }

    /**
     * Sets help_code
     *
     * @param string $help_code help_code
     *
     * @return $this
     */
    public function setHelpCode($help_code)
    {
        $this->container['help_code'] = $help_code;

        return $this;
    }

    /**
     * Gets enable
     *
     * @return int
     */
    public function getEnable()
    {
        return $this->container['enable'];
    }

    /**
     * Sets enable
     *
     * @param int $enable enable
     *
     * @return $this
     */
    public function setEnable($enable)
    {
        $this->container['enable'] = $enable;

        return $this;
    }

    /**
     * Gets is_cash
     *
     * @return int
     */
    public function getIsCash()
    {
        return $this->container['is_cash'];
    }

    /**
     * Sets is_cash
     *
     * @param int $is_cash is_cash
     *
     * @return $this
     */
    public function setIsCash($is_cash)
    {
        $this->container['is_cash'] = $is_cash;

        return $this;
    }

    /**
     * Gets is_bank
     *
     * @return int
     */
    public function getIsBank()
    {
        return $this->container['is_bank'];
    }

    /**
     * Sets is_bank
     *
     * @param int $is_bank is_bank
     *
     * @return $this
     */
    public function setIsBank($is_bank)
    {
        $this->container['is_bank'] = $is_bank;

        return $this;
    }

    /**
     * Gets is_cash_equivalent
     *
     * @return int
     */
    public function getIsCashEquivalent()
    {
        return $this->container['is_cash_equivalent'];
    }

    /**
     * Sets is_cash_equivalent
     *
     * @param int $is_cash_equivalent is_cash_equivalent
     *
     * @return $this
     */
    public function setIsCashEquivalent($is_cash_equivalent)
    {
        $this->container['is_cash_equivalent'] = $is_cash_equivalent;

        return $this;
    }

    /**
     * Gets is_qty
     *
     * @return int
     */
    public function getIsQty()
    {
        return $this->container['is_qty'];
    }

    /**
     * Sets is_qty
     *
     * @param int $is_qty is_qty
     *
     * @return $this
     */
    public function setIsQty($is_qty)
    {
        $this->container['is_qty'] = $is_qty;

        return $this;
    }

    /**
     * Gets is_currency
     *
     * @return int
     */
    public function getIsCurrency()
    {
        return $this->container['is_currency'];
    }

    /**
     * Sets is_currency
     *
     * @param int $is_currency is_currency
     *
     * @return $this
     */
    public function setIsCurrency($is_currency)
    {
        $this->container['is_currency'] = $is_currency;

        return $this;
    }

    /**
     * Gets is_assist
     *
     * @return int
     */
    public function getIsAssist()
    {
        return $this->container['is_assist'];
    }

    /**
     * Sets is_assist
     *
     * @param int $is_assist is_assist
     *
     * @return $this
     */
    public function setIsAssist($is_assist)
    {
        $this->container['is_assist'] = $is_assist;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


