<?php
/**
 * InvProductDetailResMaterialEntity
 *
 * PHP version 5
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 星辰
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace com_kingdee_service\data\entity;

use \ArrayAccess;
use \com_kingdee_service\ObjectSerializer;

/**
 * InvProductDetailResMaterialEntity Class Doc Comment
 *
 * @category Class
 * @package  com_kingdee_service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InvProductDetailResMaterialEntity implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'InvProductDetailRes.MaterialEntity';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'picture' => 'string',
        'seq' => 'int',
        'id' => 'string',
        'material_id' => 'string',
        'material_name' => 'string',
        'material_number' => 'string',
        'material_is_multi_unit' => 'bool',
        'material_is_serial' => 'bool',
        'material_is_asst_attr' => 'bool',
        'material_is_kf_period' => 'bool',
        'material_is_batch' => 'bool',
        'material_model' => 'string',
        'stock_id' => 'string',
        'stock_name' => 'string',
        'stock_number' => 'string',
        'stock_is_allow_freight' => 'bool',
        'sp_id' => 'string',
        'sp_name' => 'string',
        'sp_number' => 'string',
        'aux_prop_id' => 'string',
        'aux_prop_name' => 'string',
        'aux_prop_number' => 'string',
        'aux1_id' => 'string',
        'aux1_name' => 'string',
        'aux1_number' => 'string',
        'aux2_id' => 'string',
        'aux2_name' => 'string',
        'aux2_number' => 'string',
        'aux3_id' => 'string',
        'aux3_name' => 'string',
        'aux3_number' => 'string',
        'barcode' => 'string',
        'batch_no' => 'string',
        'pro_place' => 'string',
        'pro_reg_no' => 'string',
        'pro_license' => 'string',
        'kf_date' => 'string',
        'valid_date' => 'string',
        'kf_type' => 'string',
        'kf_period' => 'int',
        'sn' => 'string',
        'sn_list_id' => 'int',
        'base_unit_id' => 'string',
        'base_unit_name' => 'string',
        'base_unit_number' => 'string',
        'unit_id' => 'string',
        'unit_name' => 'string',
        'unit_number' => 'string',
        'aux_unit_id' => 'string',
        'aux_unit_name' => 'string',
        'aux_unit_number' => 'string',
        'conversion_rate' => 'string',
        'qty' => 'double',
        'inv_qty' => 'double',
        'base_qty' => 'double',
        'inv_base_qty' => 'double',
        'aux_qty' => 'double',
        'def_float_qty' => 'double',
        'aux_coefficient' => 'double',
        'coefficient' => 'double',
        'price' => 'double',
        'cost' => 'double',
        'unit_cost' => 'double',
        'comment' => 'string',
        'src_bill_no' => 'string',
        'src_bill_type_id' => 'string',
        'src_bill_type_name' => 'string',
        'src_bill_type_number' => 'string',
        'src_inter_id' => 'string',
        'src_bill_date' => 'string',
        'src_seq' => 'string',
        'src_entry_id' => 'string',
        'custom_entity_field' => 'map[string,string]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'picture' => null,
        'seq' => 'int32',
        'id' => null,
        'material_id' => null,
        'material_name' => null,
        'material_number' => null,
        'material_is_multi_unit' => null,
        'material_is_serial' => null,
        'material_is_asst_attr' => null,
        'material_is_kf_period' => null,
        'material_is_batch' => null,
        'material_model' => null,
        'stock_id' => null,
        'stock_name' => null,
        'stock_number' => null,
        'stock_is_allow_freight' => null,
        'sp_id' => null,
        'sp_name' => null,
        'sp_number' => null,
        'aux_prop_id' => null,
        'aux_prop_name' => null,
        'aux_prop_number' => null,
        'aux1_id' => null,
        'aux1_name' => null,
        'aux1_number' => null,
        'aux2_id' => null,
        'aux2_name' => null,
        'aux2_number' => null,
        'aux3_id' => null,
        'aux3_name' => null,
        'aux3_number' => null,
        'barcode' => null,
        'batch_no' => null,
        'pro_place' => null,
        'pro_reg_no' => null,
        'pro_license' => null,
        'kf_date' => null,
        'valid_date' => null,
        'kf_type' => null,
        'kf_period' => 'int32',
        'sn' => null,
        'sn_list_id' => 'int32',
        'base_unit_id' => null,
        'base_unit_name' => null,
        'base_unit_number' => null,
        'unit_id' => null,
        'unit_name' => null,
        'unit_number' => null,
        'aux_unit_id' => null,
        'aux_unit_name' => null,
        'aux_unit_number' => null,
        'conversion_rate' => null,
        'qty' => 'double',
        'inv_qty' => 'double',
        'base_qty' => 'double',
        'inv_base_qty' => 'double',
        'aux_qty' => 'double',
        'def_float_qty' => 'double',
        'aux_coefficient' => 'double',
        'coefficient' => 'double',
        'price' => 'double',
        'cost' => 'double',
        'unit_cost' => 'double',
        'comment' => null,
        'src_bill_no' => null,
        'src_bill_type_id' => null,
        'src_bill_type_name' => null,
        'src_bill_type_number' => null,
        'src_inter_id' => null,
        'src_bill_date' => null,
        'src_seq' => null,
        'src_entry_id' => null,
        'custom_entity_field' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'picture' => 'picture',
        'seq' => 'seq',
        'id' => 'id',
        'material_id' => 'material_id',
        'material_name' => 'material_name',
        'material_number' => 'material_number',
        'material_is_multi_unit' => 'material_is_multi_unit',
        'material_is_serial' => 'material_is_serial',
        'material_is_asst_attr' => 'material_is_asst_attr',
        'material_is_kf_period' => 'material_is_kf_period',
        'material_is_batch' => 'material_is_batch',
        'material_model' => 'material_model',
        'stock_id' => 'stock_id',
        'stock_name' => 'stock_name',
        'stock_number' => 'stock_number',
        'stock_is_allow_freight' => 'stock_is_allow_freight',
        'sp_id' => 'sp_id',
        'sp_name' => 'sp_name',
        'sp_number' => 'sp_number',
        'aux_prop_id' => 'aux_prop_id',
        'aux_prop_name' => 'aux_prop_name',
        'aux_prop_number' => 'aux_prop_number',
        'aux1_id' => 'aux1_id',
        'aux1_name' => 'aux1_name',
        'aux1_number' => 'aux1_number',
        'aux2_id' => 'aux2_id',
        'aux2_name' => 'aux2_name',
        'aux2_number' => 'aux2_number',
        'aux3_id' => 'aux3_id',
        'aux3_name' => 'aux3_name',
        'aux3_number' => 'aux3_number',
        'barcode' => 'barcode',
        'batch_no' => 'batch_no',
        'pro_place' => 'pro_place',
        'pro_reg_no' => 'pro_reg_no',
        'pro_license' => 'pro_license',
        'kf_date' => 'kf_date',
        'valid_date' => 'valid_date',
        'kf_type' => 'kf_type',
        'kf_period' => 'kf_period',
        'sn' => 'sn',
        'sn_list_id' => 'sn_list_id',
        'base_unit_id' => 'base_unit_id',
        'base_unit_name' => 'base_unit_name',
        'base_unit_number' => 'base_unit_number',
        'unit_id' => 'unit_id',
        'unit_name' => 'unit_name',
        'unit_number' => 'unit_number',
        'aux_unit_id' => 'aux_unit_id',
        'aux_unit_name' => 'aux_unit_name',
        'aux_unit_number' => 'aux_unit_number',
        'conversion_rate' => 'conversion_rate',
        'qty' => 'qty',
        'inv_qty' => 'inv_qty',
        'base_qty' => 'base_qty',
        'inv_base_qty' => 'inv_base_qty',
        'aux_qty' => 'aux_qty',
        'def_float_qty' => 'def_float_qty',
        'aux_coefficient' => 'aux_coefficient',
        'coefficient' => 'coefficient',
        'price' => 'price',
        'cost' => 'cost',
        'unit_cost' => 'unit_cost',
        'comment' => 'comment',
        'src_bill_no' => 'src_bill_no',
        'src_bill_type_id' => 'src_bill_type_id',
        'src_bill_type_name' => 'src_bill_type_name',
        'src_bill_type_number' => 'src_bill_type_number',
        'src_inter_id' => 'src_inter_id',
        'src_bill_date' => 'src_bill_date',
        'src_seq' => 'src_seq',
        'src_entry_id' => 'src_entry_id',
        'custom_entity_field' => 'custom_entity_field'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'picture' => 'setPicture',
        'seq' => 'setSeq',
        'id' => 'setId',
        'material_id' => 'setMaterialId',
        'material_name' => 'setMaterialName',
        'material_number' => 'setMaterialNumber',
        'material_is_multi_unit' => 'setMaterialIsMultiUnit',
        'material_is_serial' => 'setMaterialIsSerial',
        'material_is_asst_attr' => 'setMaterialIsAsstAttr',
        'material_is_kf_period' => 'setMaterialIsKfPeriod',
        'material_is_batch' => 'setMaterialIsBatch',
        'material_model' => 'setMaterialModel',
        'stock_id' => 'setStockId',
        'stock_name' => 'setStockName',
        'stock_number' => 'setStockNumber',
        'stock_is_allow_freight' => 'setStockIsAllowFreight',
        'sp_id' => 'setSpId',
        'sp_name' => 'setSpName',
        'sp_number' => 'setSpNumber',
        'aux_prop_id' => 'setAuxPropId',
        'aux_prop_name' => 'setAuxPropName',
        'aux_prop_number' => 'setAuxPropNumber',
        'aux1_id' => 'setAux1Id',
        'aux1_name' => 'setAux1Name',
        'aux1_number' => 'setAux1Number',
        'aux2_id' => 'setAux2Id',
        'aux2_name' => 'setAux2Name',
        'aux2_number' => 'setAux2Number',
        'aux3_id' => 'setAux3Id',
        'aux3_name' => 'setAux3Name',
        'aux3_number' => 'setAux3Number',
        'barcode' => 'setBarcode',
        'batch_no' => 'setBatchNo',
        'pro_place' => 'setProPlace',
        'pro_reg_no' => 'setProRegNo',
        'pro_license' => 'setProLicense',
        'kf_date' => 'setKfDate',
        'valid_date' => 'setValidDate',
        'kf_type' => 'setKfType',
        'kf_period' => 'setKfPeriod',
        'sn' => 'setSn',
        'sn_list_id' => 'setSnListId',
        'base_unit_id' => 'setBaseUnitId',
        'base_unit_name' => 'setBaseUnitName',
        'base_unit_number' => 'setBaseUnitNumber',
        'unit_id' => 'setUnitId',
        'unit_name' => 'setUnitName',
        'unit_number' => 'setUnitNumber',
        'aux_unit_id' => 'setAuxUnitId',
        'aux_unit_name' => 'setAuxUnitName',
        'aux_unit_number' => 'setAuxUnitNumber',
        'conversion_rate' => 'setConversionRate',
        'qty' => 'setQty',
        'inv_qty' => 'setInvQty',
        'base_qty' => 'setBaseQty',
        'inv_base_qty' => 'setInvBaseQty',
        'aux_qty' => 'setAuxQty',
        'def_float_qty' => 'setDefFloatQty',
        'aux_coefficient' => 'setAuxCoefficient',
        'coefficient' => 'setCoefficient',
        'price' => 'setPrice',
        'cost' => 'setCost',
        'unit_cost' => 'setUnitCost',
        'comment' => 'setComment',
        'src_bill_no' => 'setSrcBillNo',
        'src_bill_type_id' => 'setSrcBillTypeId',
        'src_bill_type_name' => 'setSrcBillTypeName',
        'src_bill_type_number' => 'setSrcBillTypeNumber',
        'src_inter_id' => 'setSrcInterId',
        'src_bill_date' => 'setSrcBillDate',
        'src_seq' => 'setSrcSeq',
        'src_entry_id' => 'setSrcEntryId',
        'custom_entity_field' => 'setCustomEntityField'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'picture' => 'getPicture',
        'seq' => 'getSeq',
        'id' => 'getId',
        'material_id' => 'getMaterialId',
        'material_name' => 'getMaterialName',
        'material_number' => 'getMaterialNumber',
        'material_is_multi_unit' => 'getMaterialIsMultiUnit',
        'material_is_serial' => 'getMaterialIsSerial',
        'material_is_asst_attr' => 'getMaterialIsAsstAttr',
        'material_is_kf_period' => 'getMaterialIsKfPeriod',
        'material_is_batch' => 'getMaterialIsBatch',
        'material_model' => 'getMaterialModel',
        'stock_id' => 'getStockId',
        'stock_name' => 'getStockName',
        'stock_number' => 'getStockNumber',
        'stock_is_allow_freight' => 'getStockIsAllowFreight',
        'sp_id' => 'getSpId',
        'sp_name' => 'getSpName',
        'sp_number' => 'getSpNumber',
        'aux_prop_id' => 'getAuxPropId',
        'aux_prop_name' => 'getAuxPropName',
        'aux_prop_number' => 'getAuxPropNumber',
        'aux1_id' => 'getAux1Id',
        'aux1_name' => 'getAux1Name',
        'aux1_number' => 'getAux1Number',
        'aux2_id' => 'getAux2Id',
        'aux2_name' => 'getAux2Name',
        'aux2_number' => 'getAux2Number',
        'aux3_id' => 'getAux3Id',
        'aux3_name' => 'getAux3Name',
        'aux3_number' => 'getAux3Number',
        'barcode' => 'getBarcode',
        'batch_no' => 'getBatchNo',
        'pro_place' => 'getProPlace',
        'pro_reg_no' => 'getProRegNo',
        'pro_license' => 'getProLicense',
        'kf_date' => 'getKfDate',
        'valid_date' => 'getValidDate',
        'kf_type' => 'getKfType',
        'kf_period' => 'getKfPeriod',
        'sn' => 'getSn',
        'sn_list_id' => 'getSnListId',
        'base_unit_id' => 'getBaseUnitId',
        'base_unit_name' => 'getBaseUnitName',
        'base_unit_number' => 'getBaseUnitNumber',
        'unit_id' => 'getUnitId',
        'unit_name' => 'getUnitName',
        'unit_number' => 'getUnitNumber',
        'aux_unit_id' => 'getAuxUnitId',
        'aux_unit_name' => 'getAuxUnitName',
        'aux_unit_number' => 'getAuxUnitNumber',
        'conversion_rate' => 'getConversionRate',
        'qty' => 'getQty',
        'inv_qty' => 'getInvQty',
        'base_qty' => 'getBaseQty',
        'inv_base_qty' => 'getInvBaseQty',
        'aux_qty' => 'getAuxQty',
        'def_float_qty' => 'getDefFloatQty',
        'aux_coefficient' => 'getAuxCoefficient',
        'coefficient' => 'getCoefficient',
        'price' => 'getPrice',
        'cost' => 'getCost',
        'unit_cost' => 'getUnitCost',
        'comment' => 'getComment',
        'src_bill_no' => 'getSrcBillNo',
        'src_bill_type_id' => 'getSrcBillTypeId',
        'src_bill_type_name' => 'getSrcBillTypeName',
        'src_bill_type_number' => 'getSrcBillTypeNumber',
        'src_inter_id' => 'getSrcInterId',
        'src_bill_date' => 'getSrcBillDate',
        'src_seq' => 'getSrcSeq',
        'src_entry_id' => 'getSrcEntryId',
        'custom_entity_field' => 'getCustomEntityField'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['picture'] = isset($data['picture']) ? $data['picture'] : null;
        $this->container['seq'] = isset($data['seq']) ? $data['seq'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['material_id'] = isset($data['material_id']) ? $data['material_id'] : null;
        $this->container['material_name'] = isset($data['material_name']) ? $data['material_name'] : null;
        $this->container['material_number'] = isset($data['material_number']) ? $data['material_number'] : null;
        $this->container['material_is_multi_unit'] = isset($data['material_is_multi_unit']) ? $data['material_is_multi_unit'] : null;
        $this->container['material_is_serial'] = isset($data['material_is_serial']) ? $data['material_is_serial'] : null;
        $this->container['material_is_asst_attr'] = isset($data['material_is_asst_attr']) ? $data['material_is_asst_attr'] : null;
        $this->container['material_is_kf_period'] = isset($data['material_is_kf_period']) ? $data['material_is_kf_period'] : null;
        $this->container['material_is_batch'] = isset($data['material_is_batch']) ? $data['material_is_batch'] : null;
        $this->container['material_model'] = isset($data['material_model']) ? $data['material_model'] : null;
        $this->container['stock_id'] = isset($data['stock_id']) ? $data['stock_id'] : null;
        $this->container['stock_name'] = isset($data['stock_name']) ? $data['stock_name'] : null;
        $this->container['stock_number'] = isset($data['stock_number']) ? $data['stock_number'] : null;
        $this->container['stock_is_allow_freight'] = isset($data['stock_is_allow_freight']) ? $data['stock_is_allow_freight'] : null;
        $this->container['sp_id'] = isset($data['sp_id']) ? $data['sp_id'] : null;
        $this->container['sp_name'] = isset($data['sp_name']) ? $data['sp_name'] : null;
        $this->container['sp_number'] = isset($data['sp_number']) ? $data['sp_number'] : null;
        $this->container['aux_prop_id'] = isset($data['aux_prop_id']) ? $data['aux_prop_id'] : null;
        $this->container['aux_prop_name'] = isset($data['aux_prop_name']) ? $data['aux_prop_name'] : null;
        $this->container['aux_prop_number'] = isset($data['aux_prop_number']) ? $data['aux_prop_number'] : null;
        $this->container['aux1_id'] = isset($data['aux1_id']) ? $data['aux1_id'] : null;
        $this->container['aux1_name'] = isset($data['aux1_name']) ? $data['aux1_name'] : null;
        $this->container['aux1_number'] = isset($data['aux1_number']) ? $data['aux1_number'] : null;
        $this->container['aux2_id'] = isset($data['aux2_id']) ? $data['aux2_id'] : null;
        $this->container['aux2_name'] = isset($data['aux2_name']) ? $data['aux2_name'] : null;
        $this->container['aux2_number'] = isset($data['aux2_number']) ? $data['aux2_number'] : null;
        $this->container['aux3_id'] = isset($data['aux3_id']) ? $data['aux3_id'] : null;
        $this->container['aux3_name'] = isset($data['aux3_name']) ? $data['aux3_name'] : null;
        $this->container['aux3_number'] = isset($data['aux3_number']) ? $data['aux3_number'] : null;
        $this->container['barcode'] = isset($data['barcode']) ? $data['barcode'] : null;
        $this->container['batch_no'] = isset($data['batch_no']) ? $data['batch_no'] : null;
        $this->container['pro_place'] = isset($data['pro_place']) ? $data['pro_place'] : null;
        $this->container['pro_reg_no'] = isset($data['pro_reg_no']) ? $data['pro_reg_no'] : null;
        $this->container['pro_license'] = isset($data['pro_license']) ? $data['pro_license'] : null;
        $this->container['kf_date'] = isset($data['kf_date']) ? $data['kf_date'] : null;
        $this->container['valid_date'] = isset($data['valid_date']) ? $data['valid_date'] : null;
        $this->container['kf_type'] = isset($data['kf_type']) ? $data['kf_type'] : null;
        $this->container['kf_period'] = isset($data['kf_period']) ? $data['kf_period'] : null;
        $this->container['sn'] = isset($data['sn']) ? $data['sn'] : null;
        $this->container['sn_list_id'] = isset($data['sn_list_id']) ? $data['sn_list_id'] : null;
        $this->container['base_unit_id'] = isset($data['base_unit_id']) ? $data['base_unit_id'] : null;
        $this->container['base_unit_name'] = isset($data['base_unit_name']) ? $data['base_unit_name'] : null;
        $this->container['base_unit_number'] = isset($data['base_unit_number']) ? $data['base_unit_number'] : null;
        $this->container['unit_id'] = isset($data['unit_id']) ? $data['unit_id'] : null;
        $this->container['unit_name'] = isset($data['unit_name']) ? $data['unit_name'] : null;
        $this->container['unit_number'] = isset($data['unit_number']) ? $data['unit_number'] : null;
        $this->container['aux_unit_id'] = isset($data['aux_unit_id']) ? $data['aux_unit_id'] : null;
        $this->container['aux_unit_name'] = isset($data['aux_unit_name']) ? $data['aux_unit_name'] : null;
        $this->container['aux_unit_number'] = isset($data['aux_unit_number']) ? $data['aux_unit_number'] : null;
        $this->container['conversion_rate'] = isset($data['conversion_rate']) ? $data['conversion_rate'] : null;
        $this->container['qty'] = isset($data['qty']) ? $data['qty'] : null;
        $this->container['inv_qty'] = isset($data['inv_qty']) ? $data['inv_qty'] : null;
        $this->container['base_qty'] = isset($data['base_qty']) ? $data['base_qty'] : null;
        $this->container['inv_base_qty'] = isset($data['inv_base_qty']) ? $data['inv_base_qty'] : null;
        $this->container['aux_qty'] = isset($data['aux_qty']) ? $data['aux_qty'] : null;
        $this->container['def_float_qty'] = isset($data['def_float_qty']) ? $data['def_float_qty'] : null;
        $this->container['aux_coefficient'] = isset($data['aux_coefficient']) ? $data['aux_coefficient'] : null;
        $this->container['coefficient'] = isset($data['coefficient']) ? $data['coefficient'] : null;
        $this->container['price'] = isset($data['price']) ? $data['price'] : null;
        $this->container['cost'] = isset($data['cost']) ? $data['cost'] : null;
        $this->container['unit_cost'] = isset($data['unit_cost']) ? $data['unit_cost'] : null;
        $this->container['comment'] = isset($data['comment']) ? $data['comment'] : null;
        $this->container['src_bill_no'] = isset($data['src_bill_no']) ? $data['src_bill_no'] : null;
        $this->container['src_bill_type_id'] = isset($data['src_bill_type_id']) ? $data['src_bill_type_id'] : null;
        $this->container['src_bill_type_name'] = isset($data['src_bill_type_name']) ? $data['src_bill_type_name'] : null;
        $this->container['src_bill_type_number'] = isset($data['src_bill_type_number']) ? $data['src_bill_type_number'] : null;
        $this->container['src_inter_id'] = isset($data['src_inter_id']) ? $data['src_inter_id'] : null;
        $this->container['src_bill_date'] = isset($data['src_bill_date']) ? $data['src_bill_date'] : null;
        $this->container['src_seq'] = isset($data['src_seq']) ? $data['src_seq'] : null;
        $this->container['src_entry_id'] = isset($data['src_entry_id']) ? $data['src_entry_id'] : null;
        $this->container['custom_entity_field'] = isset($data['custom_entity_field']) ? $data['custom_entity_field'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets picture
     *
     * @return string
     */
    public function getPicture()
    {
        return $this->container['picture'];
    }

    /**
     * Sets picture
     *
     * @param string $picture picture
     *
     * @return $this
     */
    public function setPicture($picture)
    {
        $this->container['picture'] = $picture;

        return $this;
    }

    /**
     * Gets seq
     *
     * @return int
     */
    public function getSeq()
    {
        return $this->container['seq'];
    }

    /**
     * Sets seq
     *
     * @param int $seq seq
     *
     * @return $this
     */
    public function setSeq($seq)
    {
        $this->container['seq'] = $seq;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets material_id
     *
     * @return string
     */
    public function getMaterialId()
    {
        return $this->container['material_id'];
    }

    /**
     * Sets material_id
     *
     * @param string $material_id material_id
     *
     * @return $this
     */
    public function setMaterialId($material_id)
    {
        $this->container['material_id'] = $material_id;

        return $this;
    }

    /**
     * Gets material_name
     *
     * @return string
     */
    public function getMaterialName()
    {
        return $this->container['material_name'];
    }

    /**
     * Sets material_name
     *
     * @param string $material_name material_name
     *
     * @return $this
     */
    public function setMaterialName($material_name)
    {
        $this->container['material_name'] = $material_name;

        return $this;
    }

    /**
     * Gets material_number
     *
     * @return string
     */
    public function getMaterialNumber()
    {
        return $this->container['material_number'];
    }

    /**
     * Sets material_number
     *
     * @param string $material_number material_number
     *
     * @return $this
     */
    public function setMaterialNumber($material_number)
    {
        $this->container['material_number'] = $material_number;

        return $this;
    }

    /**
     * Gets material_is_multi_unit
     *
     * @return bool
     */
    public function getMaterialIsMultiUnit()
    {
        return $this->container['material_is_multi_unit'];
    }

    /**
     * Sets material_is_multi_unit
     *
     * @param bool $material_is_multi_unit material_is_multi_unit
     *
     * @return $this
     */
    public function setMaterialIsMultiUnit($material_is_multi_unit)
    {
        $this->container['material_is_multi_unit'] = $material_is_multi_unit;

        return $this;
    }

    /**
     * Gets material_is_serial
     *
     * @return bool
     */
    public function getMaterialIsSerial()
    {
        return $this->container['material_is_serial'];
    }

    /**
     * Sets material_is_serial
     *
     * @param bool $material_is_serial material_is_serial
     *
     * @return $this
     */
    public function setMaterialIsSerial($material_is_serial)
    {
        $this->container['material_is_serial'] = $material_is_serial;

        return $this;
    }

    /**
     * Gets material_is_asst_attr
     *
     * @return bool
     */
    public function getMaterialIsAsstAttr()
    {
        return $this->container['material_is_asst_attr'];
    }

    /**
     * Sets material_is_asst_attr
     *
     * @param bool $material_is_asst_attr material_is_asst_attr
     *
     * @return $this
     */
    public function setMaterialIsAsstAttr($material_is_asst_attr)
    {
        $this->container['material_is_asst_attr'] = $material_is_asst_attr;

        return $this;
    }

    /**
     * Gets material_is_kf_period
     *
     * @return bool
     */
    public function getMaterialIsKfPeriod()
    {
        return $this->container['material_is_kf_period'];
    }

    /**
     * Sets material_is_kf_period
     *
     * @param bool $material_is_kf_period material_is_kf_period
     *
     * @return $this
     */
    public function setMaterialIsKfPeriod($material_is_kf_period)
    {
        $this->container['material_is_kf_period'] = $material_is_kf_period;

        return $this;
    }

    /**
     * Gets material_is_batch
     *
     * @return bool
     */
    public function getMaterialIsBatch()
    {
        return $this->container['material_is_batch'];
    }

    /**
     * Sets material_is_batch
     *
     * @param bool $material_is_batch material_is_batch
     *
     * @return $this
     */
    public function setMaterialIsBatch($material_is_batch)
    {
        $this->container['material_is_batch'] = $material_is_batch;

        return $this;
    }

    /**
     * Gets material_model
     *
     * @return string
     */
    public function getMaterialModel()
    {
        return $this->container['material_model'];
    }

    /**
     * Sets material_model
     *
     * @param string $material_model material_model
     *
     * @return $this
     */
    public function setMaterialModel($material_model)
    {
        $this->container['material_model'] = $material_model;

        return $this;
    }

    /**
     * Gets stock_id
     *
     * @return string
     */
    public function getStockId()
    {
        return $this->container['stock_id'];
    }

    /**
     * Sets stock_id
     *
     * @param string $stock_id stock_id
     *
     * @return $this
     */
    public function setStockId($stock_id)
    {
        $this->container['stock_id'] = $stock_id;

        return $this;
    }

    /**
     * Gets stock_name
     *
     * @return string
     */
    public function getStockName()
    {
        return $this->container['stock_name'];
    }

    /**
     * Sets stock_name
     *
     * @param string $stock_name stock_name
     *
     * @return $this
     */
    public function setStockName($stock_name)
    {
        $this->container['stock_name'] = $stock_name;

        return $this;
    }

    /**
     * Gets stock_number
     *
     * @return string
     */
    public function getStockNumber()
    {
        return $this->container['stock_number'];
    }

    /**
     * Sets stock_number
     *
     * @param string $stock_number stock_number
     *
     * @return $this
     */
    public function setStockNumber($stock_number)
    {
        $this->container['stock_number'] = $stock_number;

        return $this;
    }

    /**
     * Gets stock_is_allow_freight
     *
     * @return bool
     */
    public function getStockIsAllowFreight()
    {
        return $this->container['stock_is_allow_freight'];
    }

    /**
     * Sets stock_is_allow_freight
     *
     * @param bool $stock_is_allow_freight stock_is_allow_freight
     *
     * @return $this
     */
    public function setStockIsAllowFreight($stock_is_allow_freight)
    {
        $this->container['stock_is_allow_freight'] = $stock_is_allow_freight;

        return $this;
    }

    /**
     * Gets sp_id
     *
     * @return string
     */
    public function getSpId()
    {
        return $this->container['sp_id'];
    }

    /**
     * Sets sp_id
     *
     * @param string $sp_id sp_id
     *
     * @return $this
     */
    public function setSpId($sp_id)
    {
        $this->container['sp_id'] = $sp_id;

        return $this;
    }

    /**
     * Gets sp_name
     *
     * @return string
     */
    public function getSpName()
    {
        return $this->container['sp_name'];
    }

    /**
     * Sets sp_name
     *
     * @param string $sp_name sp_name
     *
     * @return $this
     */
    public function setSpName($sp_name)
    {
        $this->container['sp_name'] = $sp_name;

        return $this;
    }

    /**
     * Gets sp_number
     *
     * @return string
     */
    public function getSpNumber()
    {
        return $this->container['sp_number'];
    }

    /**
     * Sets sp_number
     *
     * @param string $sp_number sp_number
     *
     * @return $this
     */
    public function setSpNumber($sp_number)
    {
        $this->container['sp_number'] = $sp_number;

        return $this;
    }

    /**
     * Gets aux_prop_id
     *
     * @return string
     */
    public function getAuxPropId()
    {
        return $this->container['aux_prop_id'];
    }

    /**
     * Sets aux_prop_id
     *
     * @param string $aux_prop_id aux_prop_id
     *
     * @return $this
     */
    public function setAuxPropId($aux_prop_id)
    {
        $this->container['aux_prop_id'] = $aux_prop_id;

        return $this;
    }

    /**
     * Gets aux_prop_name
     *
     * @return string
     */
    public function getAuxPropName()
    {
        return $this->container['aux_prop_name'];
    }

    /**
     * Sets aux_prop_name
     *
     * @param string $aux_prop_name aux_prop_name
     *
     * @return $this
     */
    public function setAuxPropName($aux_prop_name)
    {
        $this->container['aux_prop_name'] = $aux_prop_name;

        return $this;
    }

    /**
     * Gets aux_prop_number
     *
     * @return string
     */
    public function getAuxPropNumber()
    {
        return $this->container['aux_prop_number'];
    }

    /**
     * Sets aux_prop_number
     *
     * @param string $aux_prop_number aux_prop_number
     *
     * @return $this
     */
    public function setAuxPropNumber($aux_prop_number)
    {
        $this->container['aux_prop_number'] = $aux_prop_number;

        return $this;
    }

    /**
     * Gets aux1_id
     *
     * @return string
     */
    public function getAux1Id()
    {
        return $this->container['aux1_id'];
    }

    /**
     * Sets aux1_id
     *
     * @param string $aux1_id aux1_id
     *
     * @return $this
     */
    public function setAux1Id($aux1_id)
    {
        $this->container['aux1_id'] = $aux1_id;

        return $this;
    }

    /**
     * Gets aux1_name
     *
     * @return string
     */
    public function getAux1Name()
    {
        return $this->container['aux1_name'];
    }

    /**
     * Sets aux1_name
     *
     * @param string $aux1_name aux1_name
     *
     * @return $this
     */
    public function setAux1Name($aux1_name)
    {
        $this->container['aux1_name'] = $aux1_name;

        return $this;
    }

    /**
     * Gets aux1_number
     *
     * @return string
     */
    public function getAux1Number()
    {
        return $this->container['aux1_number'];
    }

    /**
     * Sets aux1_number
     *
     * @param string $aux1_number aux1_number
     *
     * @return $this
     */
    public function setAux1Number($aux1_number)
    {
        $this->container['aux1_number'] = $aux1_number;

        return $this;
    }

    /**
     * Gets aux2_id
     *
     * @return string
     */
    public function getAux2Id()
    {
        return $this->container['aux2_id'];
    }

    /**
     * Sets aux2_id
     *
     * @param string $aux2_id aux2_id
     *
     * @return $this
     */
    public function setAux2Id($aux2_id)
    {
        $this->container['aux2_id'] = $aux2_id;

        return $this;
    }

    /**
     * Gets aux2_name
     *
     * @return string
     */
    public function getAux2Name()
    {
        return $this->container['aux2_name'];
    }

    /**
     * Sets aux2_name
     *
     * @param string $aux2_name aux2_name
     *
     * @return $this
     */
    public function setAux2Name($aux2_name)
    {
        $this->container['aux2_name'] = $aux2_name;

        return $this;
    }

    /**
     * Gets aux2_number
     *
     * @return string
     */
    public function getAux2Number()
    {
        return $this->container['aux2_number'];
    }

    /**
     * Sets aux2_number
     *
     * @param string $aux2_number aux2_number
     *
     * @return $this
     */
    public function setAux2Number($aux2_number)
    {
        $this->container['aux2_number'] = $aux2_number;

        return $this;
    }

    /**
     * Gets aux3_id
     *
     * @return string
     */
    public function getAux3Id()
    {
        return $this->container['aux3_id'];
    }

    /**
     * Sets aux3_id
     *
     * @param string $aux3_id aux3_id
     *
     * @return $this
     */
    public function setAux3Id($aux3_id)
    {
        $this->container['aux3_id'] = $aux3_id;

        return $this;
    }

    /**
     * Gets aux3_name
     *
     * @return string
     */
    public function getAux3Name()
    {
        return $this->container['aux3_name'];
    }

    /**
     * Sets aux3_name
     *
     * @param string $aux3_name aux3_name
     *
     * @return $this
     */
    public function setAux3Name($aux3_name)
    {
        $this->container['aux3_name'] = $aux3_name;

        return $this;
    }

    /**
     * Gets aux3_number
     *
     * @return string
     */
    public function getAux3Number()
    {
        return $this->container['aux3_number'];
    }

    /**
     * Sets aux3_number
     *
     * @param string $aux3_number aux3_number
     *
     * @return $this
     */
    public function setAux3Number($aux3_number)
    {
        $this->container['aux3_number'] = $aux3_number;

        return $this;
    }

    /**
     * Gets barcode
     *
     * @return string
     */
    public function getBarcode()
    {
        return $this->container['barcode'];
    }

    /**
     * Sets barcode
     *
     * @param string $barcode barcode
     *
     * @return $this
     */
    public function setBarcode($barcode)
    {
        $this->container['barcode'] = $barcode;

        return $this;
    }

    /**
     * Gets batch_no
     *
     * @return string
     */
    public function getBatchNo()
    {
        return $this->container['batch_no'];
    }

    /**
     * Sets batch_no
     *
     * @param string $batch_no batch_no
     *
     * @return $this
     */
    public function setBatchNo($batch_no)
    {
        $this->container['batch_no'] = $batch_no;

        return $this;
    }

    /**
     * Gets pro_place
     *
     * @return string
     */
    public function getProPlace()
    {
        return $this->container['pro_place'];
    }

    /**
     * Sets pro_place
     *
     * @param string $pro_place pro_place
     *
     * @return $this
     */
    public function setProPlace($pro_place)
    {
        $this->container['pro_place'] = $pro_place;

        return $this;
    }

    /**
     * Gets pro_reg_no
     *
     * @return string
     */
    public function getProRegNo()
    {
        return $this->container['pro_reg_no'];
    }

    /**
     * Sets pro_reg_no
     *
     * @param string $pro_reg_no pro_reg_no
     *
     * @return $this
     */
    public function setProRegNo($pro_reg_no)
    {
        $this->container['pro_reg_no'] = $pro_reg_no;

        return $this;
    }

    /**
     * Gets pro_license
     *
     * @return string
     */
    public function getProLicense()
    {
        return $this->container['pro_license'];
    }

    /**
     * Sets pro_license
     *
     * @param string $pro_license pro_license
     *
     * @return $this
     */
    public function setProLicense($pro_license)
    {
        $this->container['pro_license'] = $pro_license;

        return $this;
    }

    /**
     * Gets kf_date
     *
     * @return string
     */
    public function getKfDate()
    {
        return $this->container['kf_date'];
    }

    /**
     * Sets kf_date
     *
     * @param string $kf_date kf_date
     *
     * @return $this
     */
    public function setKfDate($kf_date)
    {
        $this->container['kf_date'] = $kf_date;

        return $this;
    }

    /**
     * Gets valid_date
     *
     * @return string
     */
    public function getValidDate()
    {
        return $this->container['valid_date'];
    }

    /**
     * Sets valid_date
     *
     * @param string $valid_date valid_date
     *
     * @return $this
     */
    public function setValidDate($valid_date)
    {
        $this->container['valid_date'] = $valid_date;

        return $this;
    }

    /**
     * Gets kf_type
     *
     * @return string
     */
    public function getKfType()
    {
        return $this->container['kf_type'];
    }

    /**
     * Sets kf_type
     *
     * @param string $kf_type kf_type
     *
     * @return $this
     */
    public function setKfType($kf_type)
    {
        $this->container['kf_type'] = $kf_type;

        return $this;
    }

    /**
     * Gets kf_period
     *
     * @return int
     */
    public function getKfPeriod()
    {
        return $this->container['kf_period'];
    }

    /**
     * Sets kf_period
     *
     * @param int $kf_period kf_period
     *
     * @return $this
     */
    public function setKfPeriod($kf_period)
    {
        $this->container['kf_period'] = $kf_period;

        return $this;
    }

    /**
     * Gets sn
     *
     * @return string
     */
    public function getSn()
    {
        return $this->container['sn'];
    }

    /**
     * Sets sn
     *
     * @param string $sn sn
     *
     * @return $this
     */
    public function setSn($sn)
    {
        $this->container['sn'] = $sn;

        return $this;
    }

    /**
     * Gets sn_list_id
     *
     * @return int
     */
    public function getSnListId()
    {
        return $this->container['sn_list_id'];
    }

    /**
     * Sets sn_list_id
     *
     * @param int $sn_list_id sn_list_id
     *
     * @return $this
     */
    public function setSnListId($sn_list_id)
    {
        $this->container['sn_list_id'] = $sn_list_id;

        return $this;
    }

    /**
     * Gets base_unit_id
     *
     * @return string
     */
    public function getBaseUnitId()
    {
        return $this->container['base_unit_id'];
    }

    /**
     * Sets base_unit_id
     *
     * @param string $base_unit_id base_unit_id
     *
     * @return $this
     */
    public function setBaseUnitId($base_unit_id)
    {
        $this->container['base_unit_id'] = $base_unit_id;

        return $this;
    }

    /**
     * Gets base_unit_name
     *
     * @return string
     */
    public function getBaseUnitName()
    {
        return $this->container['base_unit_name'];
    }

    /**
     * Sets base_unit_name
     *
     * @param string $base_unit_name base_unit_name
     *
     * @return $this
     */
    public function setBaseUnitName($base_unit_name)
    {
        $this->container['base_unit_name'] = $base_unit_name;

        return $this;
    }

    /**
     * Gets base_unit_number
     *
     * @return string
     */
    public function getBaseUnitNumber()
    {
        return $this->container['base_unit_number'];
    }

    /**
     * Sets base_unit_number
     *
     * @param string $base_unit_number base_unit_number
     *
     * @return $this
     */
    public function setBaseUnitNumber($base_unit_number)
    {
        $this->container['base_unit_number'] = $base_unit_number;

        return $this;
    }

    /**
     * Gets unit_id
     *
     * @return string
     */
    public function getUnitId()
    {
        return $this->container['unit_id'];
    }

    /**
     * Sets unit_id
     *
     * @param string $unit_id unit_id
     *
     * @return $this
     */
    public function setUnitId($unit_id)
    {
        $this->container['unit_id'] = $unit_id;

        return $this;
    }

    /**
     * Gets unit_name
     *
     * @return string
     */
    public function getUnitName()
    {
        return $this->container['unit_name'];
    }

    /**
     * Sets unit_name
     *
     * @param string $unit_name unit_name
     *
     * @return $this
     */
    public function setUnitName($unit_name)
    {
        $this->container['unit_name'] = $unit_name;

        return $this;
    }

    /**
     * Gets unit_number
     *
     * @return string
     */
    public function getUnitNumber()
    {
        return $this->container['unit_number'];
    }

    /**
     * Sets unit_number
     *
     * @param string $unit_number unit_number
     *
     * @return $this
     */
    public function setUnitNumber($unit_number)
    {
        $this->container['unit_number'] = $unit_number;

        return $this;
    }

    /**
     * Gets aux_unit_id
     *
     * @return string
     */
    public function getAuxUnitId()
    {
        return $this->container['aux_unit_id'];
    }

    /**
     * Sets aux_unit_id
     *
     * @param string $aux_unit_id aux_unit_id
     *
     * @return $this
     */
    public function setAuxUnitId($aux_unit_id)
    {
        $this->container['aux_unit_id'] = $aux_unit_id;

        return $this;
    }

    /**
     * Gets aux_unit_name
     *
     * @return string
     */
    public function getAuxUnitName()
    {
        return $this->container['aux_unit_name'];
    }

    /**
     * Sets aux_unit_name
     *
     * @param string $aux_unit_name aux_unit_name
     *
     * @return $this
     */
    public function setAuxUnitName($aux_unit_name)
    {
        $this->container['aux_unit_name'] = $aux_unit_name;

        return $this;
    }

    /**
     * Gets aux_unit_number
     *
     * @return string
     */
    public function getAuxUnitNumber()
    {
        return $this->container['aux_unit_number'];
    }

    /**
     * Sets aux_unit_number
     *
     * @param string $aux_unit_number aux_unit_number
     *
     * @return $this
     */
    public function setAuxUnitNumber($aux_unit_number)
    {
        $this->container['aux_unit_number'] = $aux_unit_number;

        return $this;
    }

    /**
     * Gets conversion_rate
     *
     * @return string
     */
    public function getConversionRate()
    {
        return $this->container['conversion_rate'];
    }

    /**
     * Sets conversion_rate
     *
     * @param string $conversion_rate conversion_rate
     *
     * @return $this
     */
    public function setConversionRate($conversion_rate)
    {
        $this->container['conversion_rate'] = $conversion_rate;

        return $this;
    }

    /**
     * Gets qty
     *
     * @return double
     */
    public function getQty()
    {
        return $this->container['qty'];
    }

    /**
     * Sets qty
     *
     * @param double $qty qty
     *
     * @return $this
     */
    public function setQty($qty)
    {
        $this->container['qty'] = $qty;

        return $this;
    }

    /**
     * Gets inv_qty
     *
     * @return double
     */
    public function getInvQty()
    {
        return $this->container['inv_qty'];
    }

    /**
     * Sets inv_qty
     *
     * @param double $inv_qty inv_qty
     *
     * @return $this
     */
    public function setInvQty($inv_qty)
    {
        $this->container['inv_qty'] = $inv_qty;

        return $this;
    }

    /**
     * Gets base_qty
     *
     * @return double
     */
    public function getBaseQty()
    {
        return $this->container['base_qty'];
    }

    /**
     * Sets base_qty
     *
     * @param double $base_qty base_qty
     *
     * @return $this
     */
    public function setBaseQty($base_qty)
    {
        $this->container['base_qty'] = $base_qty;

        return $this;
    }

    /**
     * Gets inv_base_qty
     *
     * @return double
     */
    public function getInvBaseQty()
    {
        return $this->container['inv_base_qty'];
    }

    /**
     * Sets inv_base_qty
     *
     * @param double $inv_base_qty inv_base_qty
     *
     * @return $this
     */
    public function setInvBaseQty($inv_base_qty)
    {
        $this->container['inv_base_qty'] = $inv_base_qty;

        return $this;
    }

    /**
     * Gets aux_qty
     *
     * @return double
     */
    public function getAuxQty()
    {
        return $this->container['aux_qty'];
    }

    /**
     * Sets aux_qty
     *
     * @param double $aux_qty aux_qty
     *
     * @return $this
     */
    public function setAuxQty($aux_qty)
    {
        $this->container['aux_qty'] = $aux_qty;

        return $this;
    }

    /**
     * Gets def_float_qty
     *
     * @return double
     */
    public function getDefFloatQty()
    {
        return $this->container['def_float_qty'];
    }

    /**
     * Sets def_float_qty
     *
     * @param double $def_float_qty def_float_qty
     *
     * @return $this
     */
    public function setDefFloatQty($def_float_qty)
    {
        $this->container['def_float_qty'] = $def_float_qty;

        return $this;
    }

    /**
     * Gets aux_coefficient
     *
     * @return double
     */
    public function getAuxCoefficient()
    {
        return $this->container['aux_coefficient'];
    }

    /**
     * Sets aux_coefficient
     *
     * @param double $aux_coefficient aux_coefficient
     *
     * @return $this
     */
    public function setAuxCoefficient($aux_coefficient)
    {
        $this->container['aux_coefficient'] = $aux_coefficient;

        return $this;
    }

    /**
     * Gets coefficient
     *
     * @return double
     */
    public function getCoefficient()
    {
        return $this->container['coefficient'];
    }

    /**
     * Sets coefficient
     *
     * @param double $coefficient coefficient
     *
     * @return $this
     */
    public function setCoefficient($coefficient)
    {
        $this->container['coefficient'] = $coefficient;

        return $this;
    }

    /**
     * Gets price
     *
     * @return double
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param double $price price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets cost
     *
     * @return double
     */
    public function getCost()
    {
        return $this->container['cost'];
    }

    /**
     * Sets cost
     *
     * @param double $cost cost
     *
     * @return $this
     */
    public function setCost($cost)
    {
        $this->container['cost'] = $cost;

        return $this;
    }

    /**
     * Gets unit_cost
     *
     * @return double
     */
    public function getUnitCost()
    {
        return $this->container['unit_cost'];
    }

    /**
     * Sets unit_cost
     *
     * @param double $unit_cost unit_cost
     *
     * @return $this
     */
    public function setUnitCost($unit_cost)
    {
        $this->container['unit_cost'] = $unit_cost;

        return $this;
    }

    /**
     * Gets comment
     *
     * @return string
     */
    public function getComment()
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param string $comment comment
     *
     * @return $this
     */
    public function setComment($comment)
    {
        $this->container['comment'] = $comment;

        return $this;
    }

    /**
     * Gets src_bill_no
     *
     * @return string
     */
    public function getSrcBillNo()
    {
        return $this->container['src_bill_no'];
    }

    /**
     * Sets src_bill_no
     *
     * @param string $src_bill_no src_bill_no
     *
     * @return $this
     */
    public function setSrcBillNo($src_bill_no)
    {
        $this->container['src_bill_no'] = $src_bill_no;

        return $this;
    }

    /**
     * Gets src_bill_type_id
     *
     * @return string
     */
    public function getSrcBillTypeId()
    {
        return $this->container['src_bill_type_id'];
    }

    /**
     * Sets src_bill_type_id
     *
     * @param string $src_bill_type_id src_bill_type_id
     *
     * @return $this
     */
    public function setSrcBillTypeId($src_bill_type_id)
    {
        $this->container['src_bill_type_id'] = $src_bill_type_id;

        return $this;
    }

    /**
     * Gets src_bill_type_name
     *
     * @return string
     */
    public function getSrcBillTypeName()
    {
        return $this->container['src_bill_type_name'];
    }

    /**
     * Sets src_bill_type_name
     *
     * @param string $src_bill_type_name src_bill_type_name
     *
     * @return $this
     */
    public function setSrcBillTypeName($src_bill_type_name)
    {
        $this->container['src_bill_type_name'] = $src_bill_type_name;

        return $this;
    }

    /**
     * Gets src_bill_type_number
     *
     * @return string
     */
    public function getSrcBillTypeNumber()
    {
        return $this->container['src_bill_type_number'];
    }

    /**
     * Sets src_bill_type_number
     *
     * @param string $src_bill_type_number src_bill_type_number
     *
     * @return $this
     */
    public function setSrcBillTypeNumber($src_bill_type_number)
    {
        $this->container['src_bill_type_number'] = $src_bill_type_number;

        return $this;
    }

    /**
     * Gets src_inter_id
     *
     * @return string
     */
    public function getSrcInterId()
    {
        return $this->container['src_inter_id'];
    }

    /**
     * Sets src_inter_id
     *
     * @param string $src_inter_id src_inter_id
     *
     * @return $this
     */
    public function setSrcInterId($src_inter_id)
    {
        $this->container['src_inter_id'] = $src_inter_id;

        return $this;
    }

    /**
     * Gets src_bill_date
     *
     * @return string
     */
    public function getSrcBillDate()
    {
        return $this->container['src_bill_date'];
    }

    /**
     * Sets src_bill_date
     *
     * @param string $src_bill_date src_bill_date
     *
     * @return $this
     */
    public function setSrcBillDate($src_bill_date)
    {
        $this->container['src_bill_date'] = $src_bill_date;

        return $this;
    }

    /**
     * Gets src_seq
     *
     * @return string
     */
    public function getSrcSeq()
    {
        return $this->container['src_seq'];
    }

    /**
     * Sets src_seq
     *
     * @param string $src_seq src_seq
     *
     * @return $this
     */
    public function setSrcSeq($src_seq)
    {
        $this->container['src_seq'] = $src_seq;

        return $this;
    }

    /**
     * Gets src_entry_id
     *
     * @return string
     */
    public function getSrcEntryId()
    {
        return $this->container['src_entry_id'];
    }

    /**
     * Sets src_entry_id
     *
     * @param string $src_entry_id src_entry_id
     *
     * @return $this
     */
    public function setSrcEntryId($src_entry_id)
    {
        $this->container['src_entry_id'] = $src_entry_id;

        return $this;
    }

    /**
     * Gets custom_entity_field
     *
     * @return map[string,string]
     */
    public function getCustomEntityField()
    {
        return $this->container['custom_entity_field'];
    }

    /**
     * Sets custom_entity_field
     *
     * @param map[string,string] $custom_entity_field custom_entity_field
     *
     * @return $this
     */
    public function setCustomEntityField($custom_entity_field)
    {
        $this->container['custom_entity_field'] = $custom_entity_field;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


